title: Amit Roy # your name (or website title) here
logo: "/assets/img/profpic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <br>
 Software Engineer at Cisco Systems India 2021
 <br>
 Research Scholar at IIT Madras 2018-2021
 <br><br>
Education: >
  <br>
  MS (By Research) -IIT Madras 2021
  <br>
  B.Tech (CSE) -IEM Kolkata 2018
  <br><br>
  <a href="/Reports/res-resume.pdf" > Resume</a> ,
  <a href="/Reports/final-thesis.pdf" > MS Thesis </a>
  <br>
Email: <a href="mailto:amit.akr.roy@gmail.com">amit.akr.roy@gmail.com </a>
  <br>
Connect: <a href="https://www.linkedin.com/in/amit-roy-iitm/">LinkedIn</a>
  <br>

theme: jekyll-theme-minimal
layout: single
classes: wide
