title: Amit Roy # your name (or website title) here
logo: "/profpic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <br>
 Software Engineer @ Cisco Systems India 2021-
 Research Scholar at IIT Madras 2018-2021
 <br> 
 Education:
 MS (By Research) - IIT Madras 2021
 B.Tech (CSE) - IEM Kolkata 2018
 
 <br><br>
  <a href="mailto:amit.akr.roy@gmail.com">amit.akr.roy@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/amit-roy-iitm/">LinkedIn Profile</a>
  <br>
  <a href="https://www.github.com/akramit/">Gihub</a> 
theme: jekyll-theme-minimal
